package cn.ghl.postgresssl.dao.entity;

// Generated 2016-5-30 16:05:05 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CspValue generated by hbm2java
 */
@Entity
@Table(name = "csp_value", schema = "public")
public class CspValue implements java.io.Serializable {

    private static final long serialVersionUID = 1783413991323342050L;

    private int     id;

    private String  statusGroup;

    private String  vdcCspValue;

    private String  descriptionEnglish;

    private String  descriptionChinese;

    private String  memo;

    private Integer unify;

    public CspValue() {
    }

    public CspValue(int id, String statusGroup) {
        this.id = id;
        this.statusGroup = statusGroup;
    }

    public CspValue(int id, String statusGroup, String vdcCspValue, String descriptionEnglish,
            String descriptionChinese, String memo, Integer unify) {
        this.id = id;
        this.statusGroup = statusGroup;
        this.vdcCspValue = vdcCspValue;
        this.descriptionEnglish = descriptionEnglish;
        this.descriptionChinese = descriptionChinese;
        this.memo = memo;
        this.unify = unify;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "status_group", nullable = false, length = 150)
    public String getStatusGroup() {
        return this.statusGroup;
    }

    public void setStatusGroup(String statusGroup) {
        this.statusGroup = statusGroup;
    }

    @Column(name = "vdc_csp_value", length = 100)
    public String getVdcCspValue() {
        return this.vdcCspValue;
    }

    public void setVdcCspValue(String vdcCspValue) {
        this.vdcCspValue = vdcCspValue;
    }

    @Column(name = "description_english", length = 200)
    public String getDescriptionEnglish() {
        return this.descriptionEnglish;
    }

    public void setDescriptionEnglish(String descriptionEnglish) {
        this.descriptionEnglish = descriptionEnglish;
    }

    @Column(name = "description_chinese", length = 200)
    public String getDescriptionChinese() {
        return this.descriptionChinese;
    }

    public void setDescriptionChinese(String descriptionChinese) {
        this.descriptionChinese = descriptionChinese;
    }

    @Column(name = "memo", length = 30)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Column(name = "unify")
    public Integer getUnify() {
        return this.unify;
    }

    public void setUnify(Integer unify) {
        this.unify = unify;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("CspValue [id=");
        builder.append(id);
        builder.append(", statusGroup=");
        builder.append(statusGroup);
        builder.append(", vdcCspValue=");
        builder.append(vdcCspValue);
        builder.append(", descriptionEnglish=");
        builder.append(descriptionEnglish);
        builder.append(", descriptionChinese=");
        builder.append(descriptionChinese);
        builder.append(", memo=");
        builder.append(memo);
        builder.append(", unify=");
        builder.append(unify);
        builder.append("]");
        return builder.toString();
    }

}
